<?php

namespace ContainerWKWqCPv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackControlleraddFavoriteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B373W1m.App\Controller\TrackController::addFavorite()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B373W1m.App\\Controller\\TrackController::addFavorite()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trackRepository' => ['privates', 'App\\Repository\\TrackRepository', 'getTrackRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'trackRepository' => 'App\\Repository\\TrackRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\TrackController::addFavorite()', $container);
    }
}
