<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container88w0CiS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container88w0CiS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container88w0CiS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container88w0CiS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container88w0CiS\App_KernelDevDebugContainer([
    'container.build_hash' => '88w0CiS',
    'container.build_id' => 'e0c2b29f',
    'container.build_time' => 1729331833,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container88w0CiS');
