<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWkkXQnW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWkkXQnW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWkkXQnW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWkkXQnW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWkkXQnW\App_KernelDevDebugContainer([
    'container.build_hash' => 'WkkXQnW',
    'container.build_id' => 'd8b28c9a',
    'container.build_time' => 1729581287,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWkkXQnW');
