<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1sPuxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1sPuxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL1sPuxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL1sPuxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL1sPuxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'L1sPuxx',
    'container.build_id' => '0f9b41fb',
    'container.build_time' => 1728893565,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL1sPuxx');
