<?php

namespace ContainerL1sPuxx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TrackController' shared autowired service.
     *
     * @return \App\Controller\TrackController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'TrackController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'TrackFactory.php';

        $container->services['App\\Controller\\TrackController'] = $instance = new \App\Controller\TrackController(($container->privates['App\\Service\\AuthSpotifyService'] ?? $container->load('getAuthSpotifyServiceService')), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), new \App\Factory\TrackFactory());

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\TrackController', $container));

        return $instance;
    }
}
